version: '3'
services:
    dps:
      image: defreitas/dns-proxy-server
      environment:
        - MG_REGISTER_CONTAINER_NAMES=1
      networks:
        - dps
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  dps:
    external: true
