sudo: required
language: c
services:
  - docker

script:
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then ./builder.bash deploy-ci; fi'
  - 'if [ "$TRAVIS_BRANCH" != "master" ]; then docker-compose rm -f && docker-compose up --build tests; fi'

branches:
  only:
  - master
  - /^(feature|bugfix).*$/
