version: '2'
services:

  # Base Image to build project
  compiler-dps:
    image: golang:1.11
    working_dir: /app/src/github.com/mageddo/dns-proxy-server
    volumes:
      - $PWD:/app/src/github.com/mageddo/dns-proxy-server
      - $PWD/builder.bash:/bin/builder.bash
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    environment:
      - TERM=xterm
      - GOPATH=/app
      - MG_WORK_DIR=/app/src/github.com/mageddo/dns-proxy-server
    hostname: dns-proxy-server.dev
    network_mode: bridge

  # Run from docker image
  prod-dps:
    image: defreitas/dns-proxy-server:2.10.2
    hostname: dns.mageddo
    volumes:
      - /opt/dns-proxy-server/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - 5380:5380
    network_mode: bridge

  # Build the project and generate binary at build folder
  prod-build-binary-dps:
    extends: compiler-dps
    command: bash -c "builder.bash build"

  # Build project and generate docker image you will need to run prod-build-binary-dps first
  prod-build-image-dps:
    build:
      context: .
      dockerfile: Dockerfile
    image: defreitas/dns-proxy-server:2.10.2

  prod-build-image-dps-arm7x86:
    build:
      context: .
      dockerfile: Dockerfile.arm7x86
    image: defreitas/dns-proxy-server-arm7x86:2.10.2

  prod-build-image-dps-arm8x64:
    build:
      context: .
      dockerfile: Dockerfile.arm8x64
    image: defreitas/dns-proxy-server-arm8x64:2.10.2

  prod-build-image-dps-arm8x86:
    build:
      context: .
      dockerfile: Dockerfile.arm8x86
    image: defreitas/dns-proxy-server-arm8x86:2.10.2

  # build the project and make the github release
  prod-ci-deploy:
    container_name: prod-ci-deploy
    extends: compiler-dps
    command: bash -c "builder.bash deploy-ci"
    environment:
      - CURRENT_BRANCH=$TRAVIS_BRANCH # current branch name
      - REPO_TOKEN=$REPO_TOKEN # github token to deploy the binary
    volumes:
      - $HOME/.gitconfig:/root/.gitconfig
