FROM ghcr.io/graalvm/graalvm-community:21.0.2-ol9-20240116 AS BUILDER

WORKDIR /app/build
COPY ./build/artifacts/native-image-source/ /app/build

RUN ls -lha &&\
  native-image --static --libc=musl -jar dns-proxy-server.jar dns-proxy-server

RUN ls -lhS &&\
    mkdir -p ./artifacts/linux-amd64-static &&\
    mv ./dns-proxy-server ./artifacts/linux-amd64-static/

ENTRYPOINT cat
