version: '2.3'
services:
  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    command: |
      bash -c '
      /bin/builder.bash deploy || exit 0 &&\
      echo "> Copying files to the host" &&\
      cp -rv /app/build/compressed-artifacts /host/build/ &&\
      cp -rv /app/build/artifacts /host/build/ &&\
      echo "Linux amd64 is done!"
      '
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ./build:/host/build
    environment:
      - CURRENT_BRANCH=${CURRENT_BRANCH}
      - REPO_TOKEN=${REPO_TOKEN}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
