version: '3'
services:
  backend:
    image: openjdk:17-jdk
    environment:
      - MG_LOG_LEVEL=DEBUG
      - MG_REGISTER_CONTAINER_NAMES=1
      - MG_RESOLVCONF=/host/etc/resolv.conf
    labels:
      - dps.container=true
    volumes:
      - ./build:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/systemd/resolve/:/host/etc/
    working_dir: /app
    command: java -jar dns-proxy-server.jar --default-dns=false
#    ports:
#      - "172.17.0.1:53:53/udp"
#      - "192.168.0.128:53:53/udp"
#      - "192.168.0.128:53:53/tcp"
#      - "127.0.0.1:53:53/udp"
#      - "127.0.0.1:53:53/tcp"
    network_mode: host
