version: '2'
services:

  # Nginx Reverse Proxy which will listen at host machine and forward the
  # request to the web-app container depending
  # on the requested hostname.
  # this app will reverse proxy all host names which connects to its 80 port querying in ${host}.container format.
  # ex: web-app.webapp will be proxied to a container with the name: web-app.webapp.container
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ':80:80'

  # Sample web app which listen a custom HTML file and registered itself as web-app.webapp.container
  web-app:
    image: nginx:1.23
    hostname: web-app.webapp.container
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  web-app-2:
    image: nginx:1.23
    hostname: web-app-2.webapp.container
