version: '2'
services:

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ':80:80'
      - ':443:443'

  web-app:
    image: nginx:1.23
    hostname: web-app.webapp.container
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
  nginx-default-web-app:
    image: nginx:1.23
    hostname: nginx.webapp.container
