version: '3'
services:
  dps:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - MG_LOG_LEVEL=ERROR
    hostname: dns.mageddo
    networks:
      dps:
        ipv4_address: 172.0.0.10

  nginx:
    image: nginx
    environment:
      - HOSTNAMES=nginx.server
    dns:
      - 172.0.0.10
    networks:
      - dps

  curl-client:
    image: alpine
    command: sh -c "apk add --update curl; watch 'curl -s -I nginx.server'"
    dns:
      - 172.0.0.10
    networks:
      - dps

networks:
  dps:
    ipam:
      config:
        - subnet: 172.0.0.0/24
