name: CD
on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "Bump version, build, generate github release, push docker images and the docs"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Deploy
        run: docker-compose -f docker-compose-deploy.yml up --force-recreate --exit-code-from deploy deploy
        env:
          # github token to deploy the binary
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
