name: CD

on:
  pull_request:

#on:
#  push:
#    branches:
#      - master

permissions:
  contents: write

env:
  CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
  # github token to deploy the binary
  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  primary_release:
    runs-on: ubuntu-latest
    outputs:
      APP_VERSION: ${{ steps.set_app_version.outputs.APP_VERSION }}
    steps:
      - name: Explain
        run: |
          echo "Releases the Jar and Linux AMD64 version"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set app version
        id: set_app_version
        run: ./gradlew setVersionOnActions

      - name: Jar and Linux AMD64 Release
        run: |
          mkdir -p ./build/ \
          && docker-compose -f docker-compose-deploy.yml up --build --force-recreate --exit-code-from deploy deploy \
          && ls -lhS ./build/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: native-image-source.jar
          path: ./build/artifacts/native-image-source/dns-proxy-server.jar

      - name: Latest version changelog extraction
        uses: kemayo/actions-recent-changelog@v1
        with:
          input: RELEASE-NOTES.md
          output: VERSION-RELEASE-NOTES.md
      - name: Check Release Notes
        run: cat ./VERSION-RELEASE-NOTES.md

      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.APP_VERSION }}
          prerelease: true
          body_path: VERSION-RELEASE-NOTES.md
          files: |
            ./build/compressed-artifacts/*

  linux_arm_release:
    runs-on: ubuntu-latest
    needs: primary_release
    steps:
      - env:
          APP_VERSION: ${{ needs.primary_release.outputs.APP_VERSION }}
        run: echo "$APP_VERSION"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/download-artifact@v3
        with:
          name: native-image-source.jar
          path: ./build/artifacts/native-image-source/dns-proxy-server.jar

      - name: Linux Arm Release
        run: |
          echo "app version=$APP_VERSION" &&\
          ls -lhS ./build/* &&\
          docker-compose -f docker-compose-deploy.yml run --build deploy-arm bash -c '
            /bin/builder.bash deploy-arm &&\
            echo "> Copying files to the host" &&\
            cp -rv /app/build/compressed-artifacts /host/build/ &&\
            echo "Linux arm64 is done!"
          ' &&\
          ls -lhS ./build/*

      # Release details will be provided by primary-release
      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.APP_VERSION }}
          append_body: true
          body: ''
          files: |
            ./build/compressed-artifacts/*
