name: CI
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'

      - name: Build and Unit Tests
        run: ./gradlew build test -i

      - name: Comp Tests
        run: ./gradlew -x check compTest -i

      - name: Native Image Integration Tests
        run: ./gradlew build -x check nativeIntTest -i
