name: CI
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
        # ['version', 'gds-token', 'java-version', 'components', 'github-token', 'set-java-home', 'cache', 'check-for-updates', 'native-image-musl', 'native-image-job-reports', 'native-image-pr-reports']
      - name: Build and Tests
        run: ./gradlew build test compTest -i

