name: Docs

on:
  pull_request:

permissions:
  contents: write

env:
  CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Deploy
        run: docker-compose -f docker-compose-deploy.yml run deploy --rm deploy /bin/builder.bash deploy-docs
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

